name: E2E – Playwright (Prod)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: e2e-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TEST_ENV: prod
      # lets TC4 paginate without rate limits
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # install Playwright browsers + system deps (no deprecated action)
      - name: Install Playwright browsers & deps
        run: npx playwright install --with-deps

      # (Optional) cache downloaded browsers to speed up runs
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      - name: Run tests (prod)
        run: npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-prod
          path: playwright-report
          retention-days: 7

      - name: Upload PR CSV artifact (TC4)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tc4-prs-csv-prod
          path: artifacts/appwrite_open_prs.csv
          if-no-files-found: ignore
          retention-days: 7
